### ISSUE TITLE
About domain shift

### ISSUE THREAD

**Issue by zhouxw12345** [cheliu-computation/MERL-ICML2024#12]
I implemented the method based on my understanding of the domain shift described in your paper, but the results differ significantly from what was reported. I would like to know: in your paper, are the prompts used in the domain shift setting derived directly from the source domain labels, or are they newly constructed prompts? Also, is it necessary to filter the target domain based on the source domain labels and then merge the target domain labels to perform zero-shot inference using only the target domain?

Below is my implementation:

```yaml
ptbxl_from_icbeb:
		target_data_path: 'ptbxl'   # Access original data
		target_split_path: 'ptbxl/super_class/ptbxl_super_class_test.csv'  # Used to obtain all labels from the source domain for prompt
		target_dataset: 'ptbxl'
		source_dataset: 'icbeb'
		target_labels: ['NORM', 'CD','STTC']  # Labels used for AUC calculation, i.e., target domain labels that match with source
		source_lables: ['NORM', '1AVB', 'CRBBB', 'CLBBB','STE', 'STD']
		mapping_direction : source_to_target # Merge predictions
		mapping:  ## Mapping from source domain labels to target domain
			NORM : ['NORM']
			CD :   ['1AVB', 'CLBBB', 'CRBBB']
			STTC :   ['STE', 'STD']
```

When `map_direction = source_to_target`, meaning the predictions are merged into coarse-grained labels:

Based on `source_lables: ['NORM', '1AVB', 'CRBBB', 'CLBBB','STE', 'STD']`, corresponding prompts are constructed, and the model predicts five classes.

Based on `target_labels: ['NORM', 'CD','STTC']`, we select all relevant samples from the target domain to build a subset for inference. The ground-truth labels are three classes: ['NORM', 'CD', 'STTC'], which also represent the coarse-grained labels.

Finally, predictions will be merged to match the coarse-grained labels via the mapping:

- ['1AVB', 'CLBBB', 'CRBBB'] → CD
- ['STE', 'STD'] → STTC

Thus, both the predictions and ground-truth labels are reduced to the same 3 classes, and AUC is calculated individually for each.

```yaml
icbeb_from_ptbxl:
      target_data_path: 'icbeb2018/records500'
      target_split_path: 'icbeb_all/icbeb_test.csv'
      target_dataset: 'icbeb'
      source_dataset: 'ptbxl'
      target_labels: ['NORM', '1AVB', 'CRBBB', 'CLBBB','STE', 'STD'] 
      source_lables: ['NORM', 'CD','STTC']
      mapping_direction : target_to_source # Merge ground-truth
      mapping:  ## Mapping from target domain labels to source domain
        NORM : ['NORM']
        CD :   ['1AVB', 'CLBBB', 'CRBBB']
        STTC :   ['STE', 'STD']

```

When `map_direction = target_to_source`, meaning the ground-truth is merged into coarse-grained labels:

Based on `source_lables: ['NORM', 'CD', 'STTC']`, corresponding prompts are constructed and the model predicts three classes.

Based on `target_labels: ['NORM', '1AVB', 'CRBBB', 'CLBBB','STE', 'STD']`, we select all relevant samples from the target domain to build the test subset. There are 6 fine-grained labels in the ground truth, which will be merged to coarse-grained labels according to the mapping (e.g., ['1AVB', 'CLBBB', 'CRBBB'] → CD). Finally, both predictions and ground-truth are reduced to 3 classes and AUC is calculated individually for each.
